[tools]
gemini-cli = "latest"
node = "24"
pnpm = "10"
lazydocker = "latest"
lazygit = "latest"
"npm:pm2" = "latest"
opencode = "latest"
zellij = "latest"
codex = "latest"
# deno = "latest"
# bun = "latest"
