# model = "openai/gpt-oss-120b:free"
# model = "tngtech/deepseek-r1t2-chimera:free"
model = "kwaipilot/kat-coder-pro:free"
model_provider = "openrouter"

[model_providers.openrouter]
name = "OpenRouter"
base_url = "https://openrouter.ai/api/v1"
env_key = "OPENROUTER_API_KEY"
wire_api = "chat"
query_params = {}